[package]
name = "rafka"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"                              
bytes = "1.3.0"                                
thiserror = "1.0.38"                      
tokio = { version = "1.37.0", features = ["full"] }
fs2 = "0.4"